#+title: BuildOS Ref

* Abstract
Qualcomm mengupdate beberapa metode untuk melakukan build. 
Untuk itu dokumen ini sesuai dengan update pada  06-08-2021

* Install Ubuntu 16.04 LTS
  1. Download ubuntu 16.04 dari [[http://releases.ubuntu.com/xenial][Release Ubuntu]].
     Peringatan: 
     + Donwload yang AMD64.
     + Download yang 16.04.x (versi 16.04.7 tidak masalah)
  2. Install development package
     + Update linux system 
       #+BEGIN_SRC bash
       sudo apt-get update
       sudo apt-get upgrade
       #+END_SRC 

     + Set up bash
       #+BEGIN_SRC bash
       sudo ln -sf /bin/bash /bin/sh
       #+END_SRC

     + Install Android tools
       #+BEGIN_SRC bash
       sudo apt-get install android-tools-adb android-tools-fastboot
       #+END_SRC
     + Install Build tools
       #+BEGIN_SRC bash
       sudo apt-get install curl git git-core gawk chrpath build-essential texinfo libz-dev
       sudo apt-get install gcc-arm-linux-gnueabi
       sudo apt-get install gcc-multilib zlib1g libssl-dev clang llvm llvm-3.8
       #+END_SRC
  3. Install Java v1.8.0 JDK
     + Menambahkan JDK Repository
       #+BEGIN_SRC bash
       sudo add-apt-repository ppa:openjdk-r/ppa
       sudo apt-get update
       #+END_SRC
     + Install Java v1.8.0 JDK dan verifikasi telah terinstall
       #+BEGIN_SRC bash
       sudo apt-get install openjdk-8-jdk
       java -version
       #+END_SRC
       Jika telah menginstall banyak java di lingkungan anda maka gunakan
       perintah berikut.
       #+BEGIN_SRC bash
       update-java-alternatives --list
       sudo update-java-alternatives -s java-1.8.0-openjdk-amd64
	#+END_SRC
  4. Check status installasi LLVM 3.8
     + Gunakan perintah berikut untuk mengecheck adakah llvm
       #+BEGIN_SRC bash
       cd /usr/lib
       ls | grep llvm
       #+END_SRC
     + Verifikasi link simbol untuk  llvm-profdata
       #+BEGIN_SRC bash
       cd /usr/bin
       ls -al | grep llvm-profdata
       #+END_SRC 
       Jika tidak ada link, buat dan verifikasi simbol link untuk llvm-profdata
       #+BEGIN_SRC bash
       sudo ln -s ../lib/llvm-3.8/bin/llvm-profdata
       ls -al | grep llvm-profdata
       #+END_SRC
  5. Install Repo
     #+BEGIN_SRC bash
     mkdir ~/bin
     PATH=~/bin:$PATH
     curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
     chmod a+x ~/bin/repo
     #+END_SRC
     + Inisiasi repo client
	#+BEGIN_SRC bash
	git config --global user.name AzizFaozi
	git config --global user.email aziz.faozi@prasimax.com
	#+END_SRC
  6. Install Samba (optional)
     
     Gunakan username_dan password dari linux machine anda
     #+BEGIN_SRC bash
     sudo apt-get install samba
     sudo gedit /etc/samba/smb.conf
     sudo smbpasswd -a faoziaziz
     sudo service smbd restart
     #+END_SRC

* Install Toolchains
Sebelum memulai mendownload toolchain buat dulu direktori toolchain
#+BEGIN_SRC bash
mkdir ~/toolchain
cd ~/toolchain
#+END_SRC
** Download LLVM 
   1. Download Semua LLVM
      #+BEGIN_SRC bash
      wget http://nemo.prasimax.net/snapdragon_sd_llvm_arm.lnx.3.9_installer_39200.2.tar
      wget http://nemo.prasimax.net/snapdragon_sd_llvm_arm.lnx.4.0_installer_40200.108-19-21_05_04_55.zip
      wget http://nemo.prasimax.net/snapdragon_sd_llvm_arm.lnx.4.0_installer_41100.108-19-21_05_08_09.zip
      #+END_SRC
      Buat direktori masing-masing versi
      #+BEGIN_SRC bash
      mkdir 3.9.2
      mkdir 4.0.2
      mkdir 4.0.11
      #+END_SRC
      Pindahkan masing-masing toolchaine kedalam direktori yang cocok 
      #+BEGIN_SRC bash
      mv snapdragon_sd_llvm_arm.lnx.3.9_installer_39200.2.tar 3.9.2
      mv snapdragon_sd_llvm_arm.lnx.4.0_installer_40200.108-19-21_05_04_55.zip 4.0.2
      mv snapdragon_sd_llvm_arm.lnx.4.0_installer_41100.108-19-21_05_08_09.zip 4.0.11
      #+END_SRC
  2. Extract masing masing llvm
     + Extract 3.9.2
       #+BEGIN_SRC bash
       cd 3.9.2
       tar -xvf snapdragon_sd_llvm_arm.lnx.3.9_installer_39200.2.tar
       tar -xzvf Snapdragon-llvm-3.9.2-linux64.tar.gz 
       cd ..
       #+END_SRC
     + Extract 4.0.2
       #+BEGIN_SRC bash
       cd 4.0.2
       unzip snapdragon_sd_llvm_arm.lnx.4.0_installer_40200.108-19-21_05_04_55.zip
       tar -xvf Snapdragon_SD_LLVM_ARM_LNX_4_0_Installer_40200_1.tar
       tar -zxvf Snapdragon-llvm-4.0.2-linux64.tar.gz
       cd ..
       #+END_SRC
     + Extract 4.0.11
       #+BEGIN_SRC bash
       cd 4.0.11
       unzip snapdragon_sd_llvm_arm.lnx.4.0_installer_41100.108-19-21_05_08_09.zip 
       tar -xvf Snapdragon_SD_LLVM_ARM_LNX_4_0_Installer_41100_1.tar 
       tar -zxvf Snapdragon-llvm-4.0.11-linux64.tar.gz 
       cd ..
       #+END_SRC
  3. Buat direktory
     #+BEGIN_SRC bash
     sudo mkdir -p /pkg/qct/software/llvm/release/arm
     sudo chmod 755 /pkg/qct/software/llvm/release/arm
     #+END_SRC
     Pindahkan semua yang sudah terekstrak ke dalam direktori diatas
     #+BEGIN_SRC bash
     cd ~/toolchain
     sudo mv 3.9.2 /pkg/qct/software/llvm/release/arm/
     sudo mv 4.0.2 /pkg/qct/software/llvm/release/arm/
     sudo mv 4.0.11 /pkg/qct/software/llvm/release/arm/
     #+END_SRC
     
     Pastikan semua direktori terpindah
     #+BEGIN_SRC bash
     cd /pkg/qct/software/llvm/release/arm
     ls -al
     #+END_SRC

* Install Hexagon 
  #+BEGIN_SRC bash
  mkdir ~/hexagon
  cd ~/hexagon
  wget http://nemo.prasimax.net/hexagon.lnx.8.2_installer_08202.308-19-21_05_09_40.zip
  unzip hexagon.lnx.8.2_installer_08202.308-19-21_05_09_40.zip 
  tar -xvf Hexagon_LNX_8_2_Installer_08202_3.tar 
  chmod +x Hexagon.LLVM_linux_installer_8.2.02.bin 
  ./Hexagon.LLVM_linux_installer_8.2.02.bin
  #+END_SRC
  Setelah itu tinggal tekan tombol next, next dst tanpa settingan lainnya.
  #+BEGIN_SRC bash
  export HEXAGON_ROOT=~/Qualcomm/HEXAGON_Tools
  export HEXAGON_RTOS_RELEASE=8.2.02
  export HEXAGON_Q6VERSION=v66
  export HEXAGON_IMAGE_ENTRY=0x8AC00000
  #+END_SRC
* Install GCC toolchain
  #+BEGIN_SRC bash
  #+END_SRC 
* Download Repo
  Download code dari repository prasimax.
  #+BEGIN_SRC bash
  cd ~
  git clone https://git.prasimax.net:2443/innovation-center/chipcode_root.git chipcode_root
  #+END_SRC
